### PR TITLE
Prometheus adapter

### PR DESCRIPTION
**Pull request by florianrusch**
I've updated the review things.

And I also fixed a bug. The custom metrics endpoint has to be `v1alpha1.custom-metrics.metrics.k8s.io`.
Further details can you find here: https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/66

### CODE REVIEW

**Comment by soorajchirag** [comment]
@florianrusch 
Were you able to test an HPA based off custom metrics with `v1alpha1.custom-metrics.metrics.k8s.io` endpoint in a 1.8 and above version?

Note that the endpoint `v1alpha1.custom-metrics.metrics.k8s.io` worked for me only on Kubernetes 1.7.

In Kubernetes 1.8 and above it would probably have to be `v1beta1.custom.metrics.k8s.io`. I havent had a chance to test this out on a newer Kubernetes version yet.

**Comment by florianrusch** [comment]
@soorajchirag You could be right. I don't really know which one is the correct one.
I've tested this on 1.10 and the metric was listed unter `custom-metrics.metrics.k8s.io/v1alpha1/`. But the hpa couldn't get it.

I will try it again later

**Comment by florianrusch** [comment]
@soorajchirag If I change the `custom-metrics-apiservice.yaml` back to the following:
```Yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  label:
    app: {{ template "k8s-prometheus-adapter.name" . }}
    chart: {{ template "k8s-prometheus-adapter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: {{ template "k8s-prometheus-adapter.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
  {{ if .Values.tls.enable -}}
  caBundle: {{ b64enc .Values.tls.ca }}
  {{- end }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: {{ if .Values.tls.enable }}false{{ else }}true{{ end }}
  groupPriorityMinimum: 100
  versionPriority: 100
```

I get this error message while upgrading:
```Plain
Error: UPGRADE FAILED: no APIService with the name "v1beta1.custom.metrics.k8s.io" found
```

**Comment by soorajchirag** [comment]
@florianrusch I am not that familiar with helm, but your error seems to be more related to how helm carries out the upgrade when there is a new resource in the picture. Did you try a helm delete and install?

**Pull request closed without merging**
